### PR TITLE
upgrade libs prepare for 2.13

### PR DESCRIPTION
**Pull request by msillence**
just upgrading libraries - everything exists for 2.13 except product-collections

### CODE REVIEW

**Comment by refond** [comment]
Any chance for 2.13 upgrade to succeed ? No project activity for four years.

**Comment by saurabh47** [comment]
I'm also looking for scala 2.13 support

**Comment by melrief** [comment]
The library is not supported anymore. I haven't been working with Scala for quite some time. You can either fork this project or use another existing CVS library.

**Comment by sentenza** [comment]
@melrief passed the ownership of this library to me. We've managed to upgrade the library to Scala v2.13.8 and dropped support for Scala v2.11.

**Pull request closed without merging**
